---
- name: Reset Password via SSM
  hosts: localhost
  gather_facts: no

  vars_files:
    - ../group_vars/aws.yml

  vars:
    username: "{{ username }}"
    password: "{{ password }}"

  tasks:
    - name: Reset password
      shell: |
        CMD_ID=$(aws ssm send-command \
        --document-name "AWS-RunShellScript" \
        --targets "Key=instanceIds,Values={{ instance_id }}" \
        --parameters '{"commands":[
        "id {{ username }} >/dev/null 2>&1 && echo {{ username }}:{{ password }} | sudo chpasswd && echo reset || echo not_found"
        ]}' \
        --query "Command.CommandId" \
        --output text \
        --region {{ region }})

        sleep 5

        aws ssm get-command-invocation \
        --command-id $CMD_ID \
        --instance-id {{ instance_id }} \
        --query "StandardOutputContent" \
        --output text \
        --region {{ region }}
      register: result

    - debug:
        msg: "{{ result.stdout }}"
